controllers/QuestionsController.php
<?php


namespace app\controllers;

use app\models\CartForm;
use app\models\Customer;
use Yii;
use yii\web\Controller;

class QuestionsController extends Controller
{
    public function actionOne() {
        return $this->render('one', [
            'data' => \Yii::$app->params['array1'],
        ]);
    }

    public function actionTwo() {
        return $this->render('two', [
            'data' => \Yii::$app->params['array1'],
        ]);
    }

    public function actionThree() {
        return $this->render('three', ['formModel' => new CartForm()]);
    }
}

controllers/ShoppingController.php
<?php


namespace app\controllers;


use app\models\Cart;
use app\models\CartForm;
use app\models\Customer;
use app\models\ShippingForm;
use http\Client;
use Shippo_Shipment;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;

class ShoppingController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionItems() {
        return $this->render('items', ['items' => CartForm::$itemList]);
    }

    public function actionCart() {

        $model = new CartForm();

        if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post())  && $model->save()) {
            Yii::$app->session->setFlash('message', 'Cart was successfully updated');
        }

        return $this->render('cart', [
            'formModel' => $model,
            'cart' => Cart::getCart(),
        ]);
    }

    public function actionCartAdd() {
        /* @var $cart Cart */
        $item = Yii::$app->request->post('items');

        $cartForm = new CartForm(['items' => [$item]]);
        if(Yii::$app->request->isPost && $cartForm->save(false)) {
            return true;
        }

        return false;
    }

    public function actionCartUpdate() {
        $cartForm = new CartForm();
        $cartForm->update(Yii::$app->request->post('itemid'), Yii::$app->request->post('quantity'));
    }

    public function actionCartRemove() {
        Cart::getCart()->removeItem(Yii::$app->request->post('itemid'));

        Yii::$app->session->set('cart', Cart::getCart());

        return true;
    }

    public function actionCheckout() {
        $shippingForm = new ShippingForm();
        $shippingForm->setCustomer(new Customer());

        if(Yii::$app->request->isPost) {
            $shippingForm->setAttributes(Yii::$app->request->post());

            // store customer details
            Yii::$app->session->set('customer', $shippingForm->getCustomer());

            \Shippo::setApiKey(Yii::$app->params['shippoToken']);
            $fromAddress = Yii::$app->params['address'];
            $toAddress = $shippingForm->getCustomer()->getShippingDetails();

            $parcel = [];
            foreach(Cart::getCart()->getItems() as $item) {
                $parcel[] = [
                    'length'=> '20',
                    'width'=> '12',
                    'height'=> '15',
                    'distance_unit'=> 'in',
                    'weight'=> '1',
                    'mass_unit'=> 'lb',
                ];
            }

            $shipment = Shippo_Shipment::create([
                'address_from'=> $fromAddress,
                'address_to'=> $toAddress,
                'parcels'=> $parcel,
                'async'=> false
            ]);

            return $shipment;
        }

        return $this->render('checkout', [
            'shippingForm' => $shippingForm,
            'cart' => Cart::getCart(),
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <script src="//kit.fontawesome.com/052a6b46ee.js" crossorigin="anonymous"></script>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-lg',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav ml-auto'],
        'items' => [
            ['label' => 'Q1', 'url' => ['/questions/one']],
            ['label' => 'Q2', 'url' => ['/questions/two']],
            ['label' => 'Shopping', 'url' => ['/shopping/items']],
            Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/site/login']]
            ) : (

                '<li class="nav-item">'
                .Html::a('<i class="far fa-shopping-cart"></i>', '/shopping/cart', ['class' => 'nav-link'])
                . '</li>'
                . '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <div class="row justify-content-lg-between">
            <div class="col-md-3">&copy; Assessment <?= date('Y') ?></div>

            <div class="col-md-3 text-right"><?= Yii::powered() ?></div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>